### ISSUE TITLE
When I follow the doc of the "hello-world-go" sample, the function build succeed but serving not running

### ISSUE THREAD

**Issue by beilineili** [OpenFunction/samples#100]
the sample is `samples/functions/knative/hello-world=go`

when i build the function and deploy it in the cluster, the four containers of the builder pod run successfully, and the state of function build is succeed. However, i can not see any `"serving ksvc"`, and when i do `"kubectl get function"`, i see that the servingstate of the function is `"created"`, not `"running"`. 

<img width="1090" alt="1" src="https://user-images.githubusercontent.com/43463041/204346059-00f7710e-0004-4c89-9396-dbe9b36e147a.png">

When i do `"kubectl get serving"`, the serving does not have `phase` or `state`

<img width="1256" alt="2" src="https://user-images.githubusercontent.com/43463041/204346333-fc031204-8b5d-443b-9aea-1d1099623bc5.png">

What happens here? When i describe "function" or "serving", i can not get any helpful message.

**Comment by wrongerror** [comment]
Please provide your environment information : 
- kubeversion
- openfunction version
- openfunction-controller-manger's logs

**Comment by beilineili** [comment]
你的邮件我已收到

**Comment by beilineili** [comment]
Thanks your reply.

My kubeversion is `1.23.7`
<img width="1256" alt="3" src="https://user-images.githubusercontent.com/43463041/204445482-0705f22c-5df5-4549-b764-e1b591e52eca.png">

The openfunction version is `0.4.0`, i am confused that why i use.`ofn install --all` but it does not install the latest version `0.8.0`.
<img width="685" alt="5" src="https://user-images.githubusercontent.com/43463041/204445671-e166cf73-e0f7-47ed-be3e-e25a37c07a36.png">
![6](https://user-images.githubusercontent.com/43463041/204445583-e4647f27-70d8-47ec-b91c-58c65372882b.png)

When i shows openfunction-controller-manger's logs, there is an error call `unknown runtime, "runtime":"knative"`, but i have installed knative-serving.
<img width="1256" alt="10" src="https://user-images.githubusercontent.com/43463041/204447788-fa7b1b5c-691b-4f36-89c2-2bf484a18a48.png">


What's more, here is my knative version, i can deploy some faasbenchmark successfully. I use `metallb` to assign external-ip for loadbalancer, and use magic dns to configure dns 
![4](https://user-images.githubusercontent.com/43463041/204445807-bf6a126d-4dbd-47bd-b3d0-de1356ca3f62.png)
<img width="1085" alt="8" src="https://user-images.githubusercontent.com/43463041/204445824-99f347bd-c799-4ac5-99af-fce741e13f4d.png">
<img width="1052" alt="9" src="https://user-images.githubusercontent.com/43463041/204446113-d76d08e2-af61-4f11-a68e-de81d85abbe4.png">

**Comment by wrongerror** [comment]
Hi, beilineili, the ofn CLI install method is deprecated, please refer to [OpenFunction installation](https://openfunction.dev/docs/getting-started/installation/#install-openfunction) .

Please ensure that the old OpenFunction and related components are properly cleaned up before helm install.

If you encounter problems during helm install，such as incorrect CRDs version，please refer to [upgrading chart ](https://github.com/OpenFunction/charts#upgrading-chart) .

**Comment by beilineili** [comment]
Thank you very much! Now i can run the serving and access function successfully.
<img width="1085" alt="1" src="https://user-images.githubusercontent.com/43463041/204461121-d6407d4d-731c-4f2e-b27a-404c5f4b83f7.png">

By the way, i think that it will be better if the latest docs can be more detailed. I watch the previous blogs to solve some questions, such as "FUNC_GOPROXY", the meanings of the four containers in builder pod, etc. And that's the reason why i use `ofn install` instead of `helm`.

**Comment by benjaminhuo** [comment]
> beilineili

@beilineili where did you find the deprecated ofn cli installation method? we need to update this doc

**Comment by beilineili** [comment]
It's in `https://openfunction.dev/docs/reference/cli/`, which shows `Use ofn to Install and Uninstall OpenFunction`. 

I follows the steps in the blog `https://openfunction.dev/zh-cn/blog/2022/03/30/%E4%BA%91%E5%8E%9F%E7%94%9F-faas-%E5%B9%B3%E5%8F%B0-openfunction-%E5%85%A5%E9%97%A8%E6%95%99%E7%A8%8B/`, so i use ofn cli installation instead of helm.

**Comment by benjaminhuo** [comment]
All removed
