### ISSUE TITLE
Is it really scaled to 0?

### ISSUE THREAD

**Issue by penghuima** [OpenFunction/samples#28]
environment：Openfuntion v 0.4  Kubernetes v1.21.5 、Kubesphere v3.2.0 
When i run pub/sub demo，It works fine .
The publisher continuously publishes messages, and the receiver can create up to 10 copies (the number of kafka topic partitions is also 10)
```sh
 subscription name: producer

 number of publishers: 2

 publish frequency: 100ms

 log frequency: 3s

 publish delay: 10s

 2021/11/05 02:12:44 OpenFuncAsync Function serving grpc: listening on port 8080

          0 published,   0/sec,   0 errors

          0 published,   0/sec,   0 errors

          0 published,   0/sec,   0 errors

 dapr client initializing for: 127.0.0.1:50001

         38 published,   3/sec,   0 errors

         98 published,   7/sec,   0 errors

        158 published,   9/sec,   0 errors

        218 published,  10/sec,   0 errors

        278 published,  12/sec,   0 errors

        338 published,  13/sec,   0 errors

        398 published,  13/sec,   0 errors

        458 published,  14/sec,   0 errors

        518 published,  14/sec,   0 errors

        578 published,  15/sec,   0 errors

        638 published,  15/sec,   0 errors

        698 published,  16/sec,   0 errors

        758 published,  16/sec,   0 errors

        818 published,  16/sec,   0 errors

        878 published,  16/sec,   0 errors

```
subscribe
![image-20211105101643571](https://cdn.jsdelivr.net/gh/penghuima/ImageBed@master/img/blog_file/PicGo-Github-ImgBed20211105101643.png)

when I deleted the publisher
```sh
[root@master16 subscriber]# kubectl delete function autoscaling-producer
function.core.openfunction.io "autoscaling-producer" deleted
```
after a while, Subscribers shrink to 0

![image-20211105103132386](https://cdn.jsdelivr.net/gh/penghuima/ImageBed@master/img/blog_file/PicGo-Github-ImgBed20211105103132.png)

But even after a long time, there will still be subscribers being created, ranging from 0-10 instances

![image](https://user-images.githubusercontent.com/43670120/140452378-b318d004-e683-44db-955c-42faedfb471c.png)

you can see the time from picture , how is this going

Bysides, is there a specification in the yarm file of the function?  like [framework-context-spec](https://github.com/OpenFunction/functions-framework/blob/main/docs/latest/OpenFunction-context-specs.md) 
The names of deployment and pod seem to be named randomly, which is not easy to distinguish

**Comment by tpiperatgod** [comment]
I will verify this issue.

For the specification of function, you can refer to [this docs](https://openfunction.dev/docs/reference/) or [in Chinese](https://openfunction.dev/zh/docs/reference/).

**Comment by tpiperatgod** [comment]
I have not reproduced this issue, so I suggest providing the logs of **keda-operator** during the time period when the issue occurred.

For the pods name, we are using a fixed prefix and a random string to name the pods associated with the function to shorten the name length of the pods. You can use the following to find the specified one:

use `kubectl get functions.core.openfunction.io` to retrieve the function list.
```shell
# kubectl get functions.core.openfunction.io
NAME                     BUILDSTATE   SERVINGSTATE   BUILDER         SERVING         AGE
autoscaling-producer     Succeeded    Running        builder-ddrtr   serving-cqcgs   10m
autoscaling-subscriber   Succeeded    Running        builder-5qmwh   serving-mkb94   8m8s
```

then use `kubectl get po -l openfunction.io/serving=<SERVING_NAME>` to retrieve the function's pods, where **<SERVING_NAME>** is the above **SERVING** name.
```shell
# kubectl get po -l openfunction.io/serving=serving-cqcgs
NAME                                                   READY   STATUS    RESTARTS   AGE
serving-cqcgs-deployment-v100-gcstp-6f85db98d9-btbcw   2/2     Running   0          28s
```

**Comment by penghuima** [comment]
I'm sorry to cause you trouble, it is indeed my personal problem.
Because I configured kafka log receiver for kubesphere, and the topic is still metric .When I delete the kafka log receiver, everything works fine, shrinking to 0

**Comment by tpiperatgod** [comment]
Ok, that's fine.
