### ISSUE TITLE
Hello-world-dotnet  build error 

### ISSUE THREAD

**Issue by geffzhang** [OpenFunction/samples#69]
cd  ./functions/knative/hello-world-dotnet
vi  function-dotnet-sample.yaml:

apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: dotnet-sample
  namespace: default
spec:
  version: "v1.0.0"
  image: "geffzhang/sample-dotnet-func:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: "openfunction/gcp-builder:v1"
    env:
      GOOGLE_FUNCTION_TARGET: "helloworld"
      GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
    srcRepo:
      url: "https://github.com/openfunction/samples.git"
      sourceSubPath: "functions/knative/hello-world-dotnet"
      revision: "release-0.6"
  serving:
    runtime: "knative" # default to knative
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent

kubectl apply -f  function-dotnet-sample.yaml

geffzhang@edgevm1:~/openfunctionsamples/functions/knative/hello-world-dotnet$ sudo kubectl get functions
[sudo] password for geffzhang:
NAME              BUILDSTATE   SERVINGSTATE   BUILDER         SERVING         URL                                              AGE
dotnet-sample     Failed                      builder-6c6ft                                                                    3d
function-sample   Succeeded    Running        builder-rk8wj   serving-24tnk   http://openfunction.io/default/function-sample   3d

geffzhang@edgevm1:~/openfunctionsamples/functions/knative/hello-world-dotnet$ sudo kubectl get builders
NAME            PHASE   STATE    REASON   AGE
builder-6c6ft   Build   Failed   Failed   75m

geffzhang@edgevm1:~/openfunctionsamples/functions/knative/hello-world-dotnet$ sudo kubectl get builds
NAME                        REGISTERED   REASON      BUILDSTRATEGYKIND      BUILDSTRATEGYNAME   CREATIONTIME
builder-6c6ft-build-4tgcn   True         Succeeded   ClusterBuildStrategy   openfunction        75m

geffzhang@edgevm1:~/openfunctionsamples/functions/knative/hello-world-dotnet$ sudo kubectl get builders -o yaml
apiVersion: v1
items:
- apiVersion: core.openfunction.io/v1beta1
  kind: Builder
  metadata:
    creationTimestamp: "2022-04-24T07:47:01Z"
    generateName: builder-
    generation: 1
    labels:
      openfunction.io/function: dotnet-sample
    managedFields:
    - apiVersion: core.openfunction.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:openfunction.io/function: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4050ecd6-fb8f-4142-9b8b-89b1e50911c4"}: {}
        f:spec:
          .: {}
          f:builder: {}
          f:env:
            .: {}
            f:GOOGLE_FUNCTION_SIGNATURE_TYPE: {}
            f:GOOGLE_FUNCTION_TARGET: {}
          f:image: {}
          f:imageCredentials:
            .: {}
            f:name: {}
          f:port: {}
          f:srcRepo:
            .: {}
            f:revision: {}
            f:sourceSubPath: {}
            f:url: {}
      manager: openfunction
      operation: Update
      time: "2022-04-24T07:47:01Z"
    - apiVersion: core.openfunction.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:phase: {}
          f:reason: {}
          f:resourceRef:
            .: {}
            f:shipwright.io/build: {}
            f:shipwright.io/buildRun: {}
          f:state: {}
      manager: openfunction
      operation: Update
      subresource: status
      time: "2022-04-24T07:47:25Z"
    name: builder-6c6ft
    namespace: default
    ownerReferences:
    - apiVersion: core.openfunction.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Function
      name: dotnet-sample
      uid: 4050ecd6-fb8f-4142-9b8b-89b1e50911c4
    resourceVersion: "6571022"
    uid: 9403e275-630a-4b80-b776-ead01b593d92
  spec:
    builder: openfunction/gcp-builder:v1
    env:
      GOOGLE_FUNCTION_SIGNATURE_TYPE: http
      GOOGLE_FUNCTION_TARGET: helloworld
    image: geffzhang/sample-dotnet-func:v1
    imageCredentials:
      name: push-secret
    port: 8080
    srcRepo:
      revision: release-0.6
      sourceSubPath: functions/knative/hello-world-dotnet
      url: https://github.com/geffzhang/openfunctionsamples.git
  status:
    phase: Build
    reason: Failed
    resourceRef:
      shipwright.io/build: builder-6c6ft-build-4tgcn
      shipwright.io/buildRun: builder-6c6ft-buildrun-lp5pz
    state: Failed
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

geffzhang@edgevm1:~/openfunctionsamples/functions/knative/hello-world-dotnet$ sudo kubectl get buildruns
NAME                           SUCCEEDED   REASON   STARTTIME   COMPLETIONTIME
builder-6c6ft-buildrun-lp5pz   False       Failed   79m         78m

sudo kubectl --namespace default logs builder-6c6ft-buildrun-lp5pz  --container=step-create
 /workspace/source/functions/knative/hello-world-dotnet/helloworld.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.GetManifests()+MoveNext()
/workspace/source/functions/knative/hello-world-dotnet/helloworld.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.LoadManifestsFromProvider(IWorkloadManifestProvider manifestProvider)
/workspace/source/functions/knative/hello-world-dotnet/helloworld.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
/workspace/source/functions/knative/hello-world-dotnet/helloworld.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir)
/workspace/source/functions/knative/hello-world-dotnet/helloworld.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
/workspace/source/functions/knative/hello-world-dotnet/helloworld.csproj : error MSB4242:    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)""
--------------------------------------------------------------------------------
Sorry your project couldn't be built.
Our documentation explains ways to configure Buildpacks to better recognise your project:
 -> https://github.com/GoogleCloudPlatform/buildpacks/blob/main/README.md
If you think you've found an issue, please report it:
 -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
--------------------------------------------------------------------------------
ERROR: failed to build: exit status 1

https://github.com/GoogleCloudPlatform/buildpacks/issues/157

**Comment by benjaminhuo** [comment]
Using the new offical gcp builder gcr.io/buildpacks/builder:v1 solved this issue？

**Comment by geffzhang** [comment]
> Using the new offical gcp builder gcr.io/buildpacks/builder:v1 solved this issue？

yes

**Comment by benjaminhuo** [comment]
I've synced the latest offical gcp builder `gcr.io/buildpacks/builder:v1` to `openfunction/gcp-builder:v1`
